import json
import os
from pathlib import Path


def _get_config_path() -> Path:
    original_user = os.environ.get("SUDO_USER", os.environ.get("USER", ""))
    if original_user and original_user != "root":
        return Path(f"/home/{original_user}") / ".config" / "LIVI" / "config.json"
    return Path.home() / ".config" / "LIVI" / "config.json"


def _load_from_json() -> dict:
    config_path = _get_config_path()
    try:
        with open(config_path) as f:
            data = json.load(f)
            print(f"[config] loaded from {config_path}")
            return data
    except FileNotFoundError:
        print(f"[config] no config.json found at {config_path}")
    except json.JSONDecodeError as e:
        print(f"[config] error parsing {config_path}: {e}")
    return {}


_JSON_CONFIG = _load_from_json()

DEVICES_FILE = _get_config_path().parent / "devices.json"


def _get_value(key: str, json_key: str, default: str) -> str:
    """config.json, then env var, then default."""
    val = _JSON_CONFIG.get(json_key, "")
    if val:
        return str(val)
    env_val = os.environ.get(key, "")
    if env_val:
        return env_val
    return default


def _list_wifi_ifaces() -> list:
    try:
        base = "/sys/class/net"
        return sorted(
            n for n in os.listdir(base) if os.path.exists(os.path.join(base, n, "wireless"))
        )
    except OSError:
        return []


def _list_bt_adapters() -> list:
    try:
        return sorted(n for n in os.listdir("/sys/class/bluetooth") if n.startswith("hci"))
    except OSError:
        return []


def _resolve_iface(configured: str, available: list) -> str:
    if configured in available or not available:
        return configured
    return available[0]


def _coerce_bool(val, default: bool) -> bool:
    if isinstance(val, bool):
        return val
    if isinstance(val, str):
        return val.strip().lower() in ("1", "true", "yes", "on")
    return default


def _get_bool(json_key: str, default: bool) -> bool:
    return _coerce_bool(_JSON_CONFIG.get(json_key, None), default)


def current_dedicated_flag() -> bool:
    """Fresh read of wifiDedicatedInterface, bypassing the import-time cache.
    The helper is long-lived, so teardown decisions must use the live value."""
    try:
        with open(_get_config_path()) as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return False
    return _coerce_bool(data.get("wifiDedicatedInterface"), False)


# Wi-Fi AP
SSID = _get_value("LIVI_SSID", "carName", "LIVI")
PASSPHRASE = _get_value("LIVI_PASSPHRASE", "wifiPassword", "12345678")
CHANNEL = int(_get_value("LIVI_CHANNEL", "wifiChannel", "36"))
COUNTRY_CODE = _get_value("LIVI_COUNTRY", "country", "DE")
WIFI_IFACE = _resolve_iface(
    _get_value("LIVI_WIFI_IFACE", "wifiInterface", "wlan0"), _list_wifi_ifaces()
)
# When the AP owns a dedicated interface it is brought up at boot by a systemd
# service, so LIVI adopts the running AP instead of starting/stopping it.
WIFI_DEDICATED = _get_bool("wifiDedicatedInterface", False)
SECURITY_TYPE = "WPA_WPA2"

# Bluetooth
BTNAME = _get_value("LIVI_BTNAME", "carName", "LIVI")
BT_ADAPTER = _resolve_iface(
    _get_value("LIVI_BT_ADAPTER", "btAdapter", "hci0"), _list_bt_adapters()
)

# CarPlay MFi authentication coprocessor over i2c (power gpio -1 = no power pin)
MFI_I2C_BUS = int(_get_value("LIVI_CP_MFI_I2C_BUS", "carPlayMfiI2cBus", "2"))
MFI_POWER_GPIO = _get_value("LIVI_CP_MFI_POWER_GPIO", "carPlayMfiPowerGpio", "-1")

# CarPlay charging current advertised to the phone over the wired link (mA)
_ALLOWED_CURRENTS_MA = (0, 500, 1000, 1500, 2100, 2400, 3000)
AVAILABLE_CURRENT_MA = int(_get_value("LIVI_CP_AVAILABLE_CURRENT_MA", "carPlayAvailableCurrentMa", "500"))
if AVAILABLE_CURRENT_MA not in _ALLOWED_CURRENTS_MA:
    AVAILABLE_CURRENT_MA = 500

CARPLAY_WIRED_START_SESSION = _get_value(
    "LIVI_CP_WIRED_START_SESSION", "carPlayWiredStartSession", "1") not in ("", "0", "false", "False")
CARPLAY_SOURCE_VERSION = _get_value("LIVI_CP_SOURCE_VERSION", "carPlaySourceVersion", "950.7.1")

# CarPlay AirPlay / Bonjour
AIRPLAY_PORT = 7000

# CarPlay AirPlay-2 pairing identity (generated by the supervisor, env only)
PK = os.environ.get("LIVI_CP_PK", "")
PI = os.environ.get("LIVI_CP_PI", "")

# CarPlay WAC metadata advertised to the phone
MANUFACTURER = "LIVI"
MODEL = "LIVI"
DEVICE_ID = "12345678"
NAME = _get_value("LIVI_CP_NAME", "carName", "LIVI")

# Verbose per-packet logging
DEBUG = os.environ.get("LIVI_CP_DEBUG", os.environ.get("DEBUG", "")) not in ("", "0", "false", "False")

# iPhone syslog tap over LIVI's usbmux socket (opt-in, wired teardown diagnosis)
CP_SYSLOG_TAP = os.environ.get("LIVI_CP_SYSLOG", "") not in ("", "0", "false", "False")
